parameters:
    app.diagnostics.allow_non_count_aware_messenger_transport: true

services:
    App\Tests\Support\Security\TestAuthenticator:
        autowire: true
        autoconfigure: true

    App\Tests\Support\PasswordReset\TestPasswordResetTokenSender: ~

    App\Service\PasswordResetTokenSenderInterface:
        alias: App\Tests\Support\PasswordReset\TestPasswordResetTokenSender
        public: true
