framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 1000
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0
            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: failed
            sync: 'sync://'

        routing:
            'App\Message\ExpireMerchantResponseMessage': async
            'App\Message\ExpirePartialAcceptanceMessage': async
            'App\Message\PartialAcceptanceReminderMessage': async
            'App\Message\SendPickupReminderMessage': async

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
                failed: 'in-memory://'
