<?php

declare(strict_types=1);

namespace App\Tests\Functional\Api;

use App\Entity\Brand;
use App\Entity\Category;
use App\Entity\ProductReference;
use App\Enum\ProductReferenceStatus;
use App\Enum\ProductUnit;

final class CategoryAdminApiTest extends FunctionalApiTestCase
{
    // ── LIST ──────────────────────────────────────────────────────────────────

    public function testAdminListsCategories(): void
    {
        $admin = $this->createUser('admin-cat-list@example.test', ['ROLE_ADMIN']);
        $cat = $this->createCategory('Produits laitiers', 'produits-laitiers');

        $response = $this->requestJson('GET', '/api/admin/categories', user: $admin);

        self::assertSame(200, $response->getStatusCode());
        $payload = $this->decodeJson($response);
        self::assertSame(1, $payload['total']);
        self::assertSame(1, $payload['page']);
        self::assertSame(20, $payload['limit']);
        self::assertCount(1, $payload['items']);
        self::assertSame($cat->getId()->toRfc4122(), $payload['items'][0]['id']);
        self::assertSame('Produits laitiers', $payload['items'][0]['name_fr']);
        self::assertSame('produits-laitiers', $payload['items'][0]['slug']);
        self::assertTrue($payload['items'][0]['is_active']);
        self::assertArrayHasKey('created_at', $payload['items'][0]);
        self::assertArrayHasKey('updated_at', $payload['items'][0]);
    }

    public function testListPaginationDefaultsAndLimit(): void
    {
        $admin = $this->createUser('admin-cat-pagination@example.test', ['ROLE_ADMIN']);
        for ($i = 1; $i <= 3; ++$i) {
            $this->createCategory('Catégorie '.$i, 'categorie-'.$i);
        }

        $pageOne = $this->decodeJson($this->requestJson('GET', '/api/admin/categories?page=1&limit=2', user: $admin));
        $pageTwo = $this->decodeJson($this->requestJson('GET', '/api/admin/categories?page=2&limit=2', user: $admin));

        self::assertSame(3, $pageOne['total']);
        self::assertSame(2, $pageOne['limit']);
        self::assertCount(2, $pageOne['items']);
        self::assertSame(3, $pageTwo['total']);
        self::assertCount(1, $pageTwo['items']);
    }

    // ── GET ITEM ──────────────────────────────────────────────────────────────

    public function testAdminGetsCategoryDetail(): void
    {
        $admin = $this->createUser('admin-cat-detail@example.test', ['ROLE_ADMIN']);
        $cat = $this->createCategory('Boissons', 'boissons', nameAr: 'مشروبات');

        $response = $this->requestJson('GET', \sprintf('/api/admin/categories/%s', $cat->getId()), user: $admin);

        self::assertSame(200, $response->getStatusCode());
        $payload = $this->decodeJson($response);
        self::assertSame($cat->getId()->toRfc4122(), $payload['id']);
        self::assertSame('Boissons', $payload['name_fr']);
        self::assertSame('مشروبات', $payload['name_ar']);
        self::assertSame('boissons', $payload['slug']);
        self::assertTrue($payload['is_active']);
        self::assertSame(0, $payload['sort_order']);
        self::assertNull($payload['parent_id']);
    }

    public function testGetCategoryReturns404WhenAbsent(): void
    {
        $admin = $this->createUser('admin-cat-404@example.test', ['ROLE_ADMIN']);

        $response = $this->requestJson('GET', '/api/admin/categories/00000000-0000-0000-0000-000000000001', user: $admin);

        self::assertSame(404, $response->getStatusCode());
    }

    // ── POST ──────────────────────────────────────────────────────────────────

    public function testAdminCreatesCategory(): void
    {
        $admin = $this->createUser('admin-cat-create@example.test', ['ROLE_ADMIN']);

        $response = $this->requestJson('POST', '/api/admin/categories', [
            'nameFr' => 'Épicerie fine',
            'nameAr' => 'بقالة فاخرة',
        ], $admin);

        self::assertSame(201, $response->getStatusCode());
        $payload = $this->decodeJson($response);
        self::assertSame('Épicerie fine', $payload['name_fr']);
        self::assertSame('بقالة فاخرة', $payload['name_ar']);
        self::assertSame('epicerie-fine', $payload['slug']);
        self::assertTrue($payload['is_active']);
        self::assertArrayHasKey('id', $payload);
    }

    public function testAdminCreatesCategpryWithExplicitSlug(): void
    {
        $admin = $this->createUser('admin-cat-slug@example.test', ['ROLE_ADMIN']);

        $response = $this->requestJson('POST', '/api/admin/categories', [
            'nameFr' => 'Viandes',
            'slug' => 'viandes-fraiches',
        ], $admin);

        self::assertSame(201, $response->getStatusCode());
        self::assertSame('viandes-fraiches', $this->decodeJson($response)['slug']);
    }

    public function testSlugAutoGeneratedAndUniqueWithSuffix(): void
    {
        $admin = $this->createUser('admin-cat-slug-suffix@example.test', ['ROLE_ADMIN']);
        $this->createCategory('Épicerie', 'epicerie');

        $response = $this->requestJson('POST', '/api/admin/categories', ['nameFr' => 'Épicerie'], $admin);

        self::assertSame(201, $response->getStatusCode());
        self::assertSame('epicerie-2', $this->decodeJson($response)['slug']);
    }

    public function testExplicitDuplicateSlugIsRejected(): void
    {
        $admin = $this->createUser('admin-cat-dup-slug@example.test', ['ROLE_ADMIN']);
        $this->createCategory('Fruits', 'fruits');

        $response = $this->requestJson('POST', '/api/admin/categories', [
            'nameFr' => 'Fruits bio',
            'slug' => 'fruits',
        ], $admin);

        self::assertSame(422, $response->getStatusCode());
    }

    public function testCreateCategoryRequiresNameFr(): void
    {
        $admin = $this->createUser('admin-cat-no-name@example.test', ['ROLE_ADMIN']);

        $response = $this->requestJson('POST', '/api/admin/categories', ['nameAr' => 'فقط عربي'], $admin);

        self::assertSame(422, $response->getStatusCode());
    }

    // ── PATCH ─────────────────────────────────────────────────────────────────

    public function testAdminPatchesCategory(): void
    {
        $admin = $this->createUser('admin-cat-patch@example.test', ['ROLE_ADMIN']);
        $cat = $this->createCategory('Surgelés', 'surgeles');

        $response = $this->requestJson(
            'PATCH',
            \sprintf('/api/admin/categories/%s', $cat->getId()),
            ['nameFr' => 'Produits surgelés'],
            $admin,
        );

        self::assertSame(200, $response->getStatusCode());
        self::assertSame('Produits surgelés', $this->decodeJson($response)['name_fr']);
        self::assertSame('surgeles', $this->decodeJson($response)['slug']);
    }

    public function testPatchCategoryIsPartial(): void
    {
        $admin = $this->createUser('admin-cat-patch-partial@example.test', ['ROLE_ADMIN']);
        $cat = $this->createCategory('Conserves', 'conserves', nameAr: 'معلبات');

        $response = $this->requestJson(
            'PATCH',
            \sprintf('/api/admin/categories/%s', $cat->getId()),
            ['isActive' => false],
            $admin,
        );

        self::assertSame(200, $response->getStatusCode());
        $payload = $this->decodeJson($response);
        self::assertFalse($payload['is_active']);
        self::assertSame('Conserves', $payload['name_fr']);
        self::assertSame('معلبات', $payload['name_ar']);
    }

    public function testPatchCategoryReturns404WhenAbsent(): void
    {
        $admin = $this->createUser('admin-cat-patch-404@example.test', ['ROLE_ADMIN']);

        $response = $this->requestJson(
            'PATCH',
            '/api/admin/categories/00000000-0000-0000-0000-000000000001',
            ['nameFr' => 'X'],
            $admin,
        );

        self::assertSame(404, $response->getStatusCode());
    }

    // ── DELETE ────────────────────────────────────────────────────────────────

    public function testAdminPhysicallyDeletesUnlinkedCategory(): void
    {
        $admin = $this->createUser('admin-cat-delete@example.test', ['ROLE_ADMIN']);
        $cat = $this->createCategory('À supprimer', 'a-supprimer');
        $id = $cat->getId()->toRfc4122();

        $deleteResponse = $this->requestJson('DELETE', \sprintf('/api/admin/categories/%s', $id), user: $admin);
        $getResponse = $this->requestJson('GET', \sprintf('/api/admin/categories/%s', $id), user: $admin);

        self::assertSame(204, $deleteResponse->getStatusCode());
        self::assertSame(404, $getResponse->getStatusCode());
    }

    public function testAdminLogicallyDeletesCategoryLinkedToProducts(): void
    {
        $admin = $this->createUser('admin-cat-logical-delete@example.test', ['ROLE_ADMIN']);
        $cat = $this->createCategory('Liée aux produits', 'liee-produits');
        $this->createProductReferenceForCategory($cat);
        $id = $cat->getId()->toRfc4122();

        $deleteResponse = $this->requestJson('DELETE', \sprintf('/api/admin/categories/%s', $id), user: $admin);
        $getResponse = $this->requestJson('GET', \sprintf('/api/admin/categories/%s', $id), user: $admin);

        self::assertSame(204, $deleteResponse->getStatusCode());
        self::assertSame(200, $getResponse->getStatusCode());
        self::assertFalse($this->decodeJson($getResponse)['is_active']);
    }

    public function testDeleteCategoryReturns404WhenAbsent(): void
    {
        $admin = $this->createUser('admin-cat-delete-404@example.test', ['ROLE_ADMIN']);

        $response = $this->requestJson('DELETE', '/api/admin/categories/00000000-0000-0000-0000-000000000001', user: $admin);

        self::assertSame(404, $response->getStatusCode());
    }

    // ── ACCESS CONTROL ────────────────────────────────────────────────────────

    public function testAnonymousIsRejected(): void
    {
        $cat = $this->createCategory('Test', 'test-anon');

        self::assertSame(401, $this->requestJson('GET', '/api/admin/categories')->getStatusCode());
        self::assertSame(401, $this->requestJson('GET', \sprintf('/api/admin/categories/%s', $cat->getId()))->getStatusCode());
        self::assertSame(401, $this->requestJson('POST', '/api/admin/categories', ['nameFr' => 'X'])->getStatusCode());
        self::assertSame(401, $this->requestJson('PATCH', \sprintf('/api/admin/categories/%s', $cat->getId()), ['nameFr' => 'X'])->getStatusCode());
        self::assertSame(401, $this->requestJson('DELETE', \sprintf('/api/admin/categories/%s', $cat->getId()))->getStatusCode());
    }

    public function testMerchantIsRejected(): void
    {
        $merchant = $this->createUser('merchant-cat@example.test', ['ROLE_MERCHANT']);
        $cat = $this->createCategory('Test marchand', 'test-marchand');

        self::assertSame(403, $this->requestJson('GET', '/api/admin/categories', user: $merchant)->getStatusCode());
        self::assertSame(403, $this->requestJson('GET', \sprintf('/api/admin/categories/%s', $cat->getId()), user: $merchant)->getStatusCode());
        self::assertSame(403, $this->requestJson('POST', '/api/admin/categories', ['nameFr' => 'X'], $merchant)->getStatusCode());
        self::assertSame(403, $this->requestJson('PATCH', \sprintf('/api/admin/categories/%s', $cat->getId()), ['nameFr' => 'X'], $merchant)->getStatusCode());
        self::assertSame(403, $this->requestJson('DELETE', \sprintf('/api/admin/categories/%s', $cat->getId()), user: $merchant)->getStatusCode());
    }

    public function testCustomerIsRejected(): void
    {
        $customer = $this->createUser('customer-cat@example.test', ['ROLE_CUSTOMER']);
        $cat = $this->createCategory('Test client', 'test-client');

        self::assertSame(403, $this->requestJson('GET', '/api/admin/categories', user: $customer)->getStatusCode());
        self::assertSame(403, $this->requestJson('GET', \sprintf('/api/admin/categories/%s', $cat->getId()), user: $customer)->getStatusCode());
        self::assertSame(403, $this->requestJson('POST', '/api/admin/categories', ['nameFr' => 'X'], $customer)->getStatusCode());
        self::assertSame(403, $this->requestJson('PATCH', \sprintf('/api/admin/categories/%s', $cat->getId()), ['nameFr' => 'X'], $customer)->getStatusCode());
        self::assertSame(403, $this->requestJson('DELETE', \sprintf('/api/admin/categories/%s', $cat->getId()), user: $customer)->getStatusCode());
    }

    // ── HELPERS ───────────────────────────────────────────────────────────────

    private function createCategory(string $nameFr, string $slug, ?string $nameAr = null): Category
    {
        $category = (new Category())
            ->setNameFr($nameFr)
            ->setNameAr($nameAr)
            ->setSlug($slug)
            ->setActive(true);

        $this->entityManager->persist($category);
        $this->entityManager->flush();

        return $category;
    }

    private function createProductReferenceForCategory(Category $category): ProductReference
    {
        $brand = (new Brand())
            ->setCanonicalName('Brand for cat test')
            ->setSlug('brand-cat-test-'.$category->getId()->toRfc4122())
            ->setActive(true);
        $productReference = (new ProductReference())
            ->setBrand($brand)
            ->setCategory($category)
            ->setNameFr('Produit lié')
            ->setUnit(ProductUnit::Piece)
            ->setStatus(ProductReferenceStatus::Approved);

        $this->entityManager->persist($brand);
        $this->entityManager->persist($productReference);
        $this->entityManager->flush();

        return $productReference;
    }
}
