[program:messenger-worker]
command=php /var/www/html/bin/console messenger:consume async --time-limit=3600 --memory-limit=128M
directory=/var/www/html
user=www-data
numprocs=1
startsecs=0
autostart=true
autorestart=true
startretries=10
stderr_logfile=/var/log/supervisor/messenger-worker.err.log
stdout_logfile=/var/log/supervisor/messenger-worker.out.log
